/// テスト用の小さなパンフレットデータ。
/// 実際の data/2025/festival.json から、日付の判定に必要な部分だけを抜き出したもの。
const testFestivalJson = <String, dynamic>{
  'schemaVersion': 1,
  'updatedAt': '2026-09-20T00:00:00+09:00',
  'edition': {
    'year': 2025,
    'number': 72,
    'name': '第72回中京大学祭',
    'campus': '名古屋キャンパス',
    'theme': {'kanji': '月', 'reading': 'つき'},
    'days': [
      {'date': '2025-11-01', 'label': '11月1日(土)', 'open': '12:00', 'close': '18:00'},
      {'date': '2025-11-02', 'label': '11月2日(日)', 'open': '10:00', 'close': '18:00'},
      {'date': '2025-11-03', 'label': '11月3日(月)', 'open': '10:00', 'close': '17:00'},
    ],
  },
  'venues': [
    {'id': 'galleria', 'name': 'ガレリアステージ', 'building': '0号館'},
    {'id': 'gym', 'name': '体育館', 'showGymDirections': true},
  ],
  'eventCategories': [
    {'id': 'stage', 'name': 'ステージ企画'},
    {'id': 'sports', 'name': 'スポーツ企画'},
  ],
  'events': [
    {
      'id': 'ev-1101-shodo',
      'category': 'stage',
      'series': '中京フェス',
      'date': '2025-11-01',
      'start': '12:10',
      'end': '12:40',
      'venueId': 'galleria',
      'title': '中京大学文化会書道部',
      'notify': true,
    },
    {
      'id': 'ev-1101-amygdalin',
      'category': 'stage',
      'series': '中京フェス',
      'date': '2025-11-01',
      'start': '13:50',
      'end': '14:35',
      'venueId': 'galleria',
      'title': 'Mr.AMYGDALIN',
      'notify': true,
    },
    {
      'id': 'ev-1101-basketball',
      'category': 'sports',
      'date': '2025-11-01',
      'start': '12:30',
      'end': '15:30',
      'venueId': 'gym',
      'title': 'バスケ大会',
      'notify': true,
    },
    {
      'id': 'ev-1102-beat',
      'category': 'stage',
      'series': '中京フェス',
      'date': '2025-11-02',
      'start': '13:00',
      'end': '13:30',
      'venueId': 'galleria',
      'title': 'ダンス部BEAT',
      'status': 'cancelled',
      'notify': false,
    },
    {
      'id': 'ev-1103-dopers',
      'category': 'stage',
      'series': 'CHUKYO FES',
      'date': '2025-11-03',
      'start': '10:45',
      'end': '11:25',
      'venueId': 'galleria',
      'title': 'DOPERS',
      'notify': true,
    },
  ],
  'projectCategories': [
    {'id': 'classroom', 'name': '教室企画'},
  ],
  'projects': [
    {
      'id': 'pj-boardgame',
      'category': 'classroom',
      'title': 'ボードゲーム企画',
      'location': {'building': '1号館', 'floor': '3階', 'rooms': ['131']},
      'schedule': [
        {'date': '2025-11-01', 'start': '12:00', 'end': '18:00', 'lastEntry': '17:30'},
        {'date': '2025-11-02', 'start': '10:00', 'end': '18:00', 'lastEntry': '17:30'},
        {'date': '2025-11-03', 'start': '10:00', 'end': '17:00', 'lastEntry': '16:30'},
      ],
    },
  ],
  'boothAreas': [],
  'booths': [],
};
